## Docker compose file for chromadb:

services:
  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chromadb
    ports:
      - "8575:8575"
    expose:
      - "8575"
    volumes:
      - ~/.local/share/vectorcode/chromadb/:/data/
      - ./chroma_config.yaml:/config.yaml
    environment:
      - CHROMA_DB_DIR=/data
      - CHROMA_HOST_PORT=8575

    restart: unless-stopped
